codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  status:
    project:
      default:
        target: 80%
        threshold: 1%
        informational: false
    patch:
      default:
        target: 75%
        threshold: 0%
        informational: false

ignore:
  - "tests/**"
  - "scripts/**"
  - "docs/**"
