name: CI

on:
  push:
    branches: ["main"]
  pull_request:

permissions: read-all

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Harden runner
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2
        with:
          egress-policy: audit
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      - name: Setup Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version: "3.12"
      - name: Install system deps (libsodium for PyNaCl if needed)
        run: sudo apt-get update && sudo apt-get install -y libsodium23 || true
      - name: Install deps (hash-locked)
        run: |
          python -m pip install --upgrade pip
          pip install --no-deps --require-hashes -r requirements.lock -r requirements-dev.lock
      - name: Lint
        run: |
          python -m ruff check src tests
          python -m ruff format --check src tests
      - name: Tests
        run: |
          export PYTHONPATH=./src
          python -m pytest -q