name: Fuzzing (PR)

on:
  pull_request:
    paths:
      - 'src/**/*.py'
      - 'fuzz/**'
      - '.github/workflows/fuzzing-pr.yml'

permissions: read-all

jobs:
  fuzz:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Harden runner
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2
        with:
          egress-policy: audit
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-fuzz.txt
      - name: Run fuzzers (short)
        uses: google/clusterfuzzlite/actions/run_fuzzers@82652fb49e77bc29c35da1167bb286e93c6bcc05 # v1
        with:
          fuzz-seconds: 120
          language: python
          sanitizer: 'none'
          github-token: ${{ secrets.GITHUB_TOKEN }}
