name: Mutation tests (optional)

on:
  workflow_dispatch:

permissions: read-all

jobs:
  mutmut:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Harden runner
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2
        with:
          egress-policy: audit
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      - name: Setup Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version: '3.12'
      - name: Install deps and mutmut
        run: |
          python -m pip install --upgrade pip
          pip install --no-deps --require-hashes -r requirements.lock -r requirements-dev.lock || true
          pip install mutmut==3.2.0
      - name: Run mutation tests on critical modules (non-blocking)
        run: |
          export PYTHONPATH=./src
          mutmut run --paths-to-mutate src/signet_api src/signet_sdk || true
          mutmut results || true
