name: Publish (PyPI)

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

permissions: read-all

jobs:
  build-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Harden runner
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2
        with:
          egress-policy: audit
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version: '3.11'
      - name: Build artifacts
        run: |
          python -m pip install --upgrade pip
          pip install --require-hashes -r requirements.lock
          pip install --require-hashes -r requirements-dev.lock
          python -m build
          python -m twine check dist/*
      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          python -m pip install --upgrade pip
          pip install --require-hashes -r requirements.lock
          pip install --require-hashes -r requirements-dev.lock
          twine upload --non-interactive dist/*
      - name: Record artifact hashes
        run: |
          (shasum -a 256 dist/* || sha256sum dist/*) > dist/hashes.sha256
      - name: Upload build artifacts
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: signet-sdk-dist
          path: |
            dist/*.whl
            dist/*.tar.gz
            dist/hashes.sha256