name: SBOM (CycloneDX)

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions: read-all

jobs:
  sbom:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Harden runner
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2
        with:
          egress-policy: audit
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      - name: Setup Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version: '3.12'
      - name: Install CycloneDX and deps (locked runtime only)
        run: |
          python -m pip install --upgrade pip
          pip install --no-deps --require-hashes -r requirements.lock
          pip install cyclonedx-bom==4.3.12
      - name: Generate SBOM (CycloneDX JSON)
        run: cyclonedx-bom -o sbom.json --format json
      - name: Upload SBOM
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: sbom-cyclonedx
          path: sbom.json
