name: OpenSSF Scorecard

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

# Minimal, read-only by default; Scorecard needs security-events: write and id-token: write in this job.
permissions:
  contents: read

jobs:
  scorecard:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write   # to upload SARIF to code scanning
      id-token: write          # required by Scorecard action even if publish_results=false (OIDC)
    steps:
      - name: Harden runner
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2
        with:
          egress-policy: audit
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      - name: Run Scorecard (SARIF only; no publish/sign)
        uses: ossf/scorecard-action@05b42c624433fc40578a4040d5cf5e36ddca8cde # v2.4.2
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload SARIF to code scanning
        uses: github/codeql-action/upload-sarif@b36bf259c813715f76eafece573914b94412cd13 # v3
        with:
          sarif_file: results.sarif
