name: OpenSSF Scorecard

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 8 * * 1'  # weekly

permissions:
  contents: read

jobs:
  analysis:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      id-token: write
      contents: read
      actions: read
    steps:
      - name: Harden runner
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Scorecard
        uses: ossf/scorecard-action@v2.1.0
        with:
            results_file: results.sarif
            results_format: sarif
            publish_results: true
      - name: Upload to Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
