name: Type check (mypy)

on:
  push:
    branches: ["main"]
  pull_request:

permissions: read-all

jobs:
  mypy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Harden runner
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2
        with:
          egress-policy: audit
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      - name: Setup Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version: '3.12'
      - name: Install deps (locked) and mypy (pinned)
        run: |
          python -m pip install --upgrade pip
          pip install --no-deps --require-hashes -r requirements.lock -r requirements-dev.lock || true
          pip install mypy==1.11.2
      - name: Type check
        run: |
          export PYTHONPATH=./src
          python -m mypy src --python-version 3.12 --ignore-missing-imports --warn-unused-ignores --show-error-codes --pretty
